dist: bionic
language: node_js
node_js:
  - 14

before_install:
- sudo apt-get -y install libev-dev
- npm i -g esy

install: esy install

script: 
- esy build
- zip -r latest appspec.yml _build/default/bin/Hello.exe scripts
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip

cache:
  directories:
  - $HOME/.esy/source/i
  - $HOME/.esy/3___________________________________________________________________/i

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: matheussbernardo/monadministranto
  bucket: telegramdeploy
  region: us-east-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: telegramdeploy
  key: latest.zip
  bundle_type: zip
  application: administrantodeploy
  deployment_group: deploydobot
  region: us-east-2
  on: *2


addons:
  apt:
    update: true